using System;
using Unison.Core.Models;

namespace Unison.Core.Helpers
{
    /// <summary>
    /// Shared JID normalization (device suffix, LID instance, phone user part).
    /// </summary>
    public static class JidHelper
    {
        /// <summary>
        /// Normalizes a WhatsApp JID: trim, strip device suffix, collapse LID/instance noise.
        /// </summary>
        public static string Normalize(string jid)
        {
            if (string.IsNullOrEmpty(jid))
            {
                return jid;
            }

            jid = jid.Trim();
            if (jid.EndsWith("@g.us", StringComparison.OrdinalIgnoreCase))
            {
                return jid;
            }

            int atIndex = jid.IndexOf('@');
            if (atIndex <= 0 || atIndex >= jid.Length - 1)
            {
                return jid;
            }

            string user = jid.Substring(0, atIndex).Trim();
            string server = jid.Substring(atIndex + 1).Trim().ToLowerInvariant();

            if (user.Contains(":"))
            {
                user = user.Split(':')[0];
            }

            // Remove instance suffix for LIDs.
            // For @s.whatsapp.net keep non-zero dotted identifiers (LID-like) intact,
            // but collapse ".0" user aliases generated by some device JIDs.
            if (server == "lid" && user.Contains("."))
            {
                user = user.Split('.')[0];
            }
            else if (server.Equals("s.whatsapp.net", StringComparison.OrdinalIgnoreCase) && user.Contains("."))
            {
                int lastDot = user.LastIndexOf('.');
                if (lastDot > 0)
                {
                    string prefix = user.Substring(0, lastDot);
                    string suffix = user.Substring(lastDot + 1);
                    if (suffix == "0")
                    {
                        user = prefix;
                    }
                }
            }

            return user + "@" + server;
        }

        /// <summary>
        /// Phone digits from a PN JID (@s.whatsapp.net); otherwise null.
        /// </summary>
        public static string TryPhoneFromJid(string jid)
        {
            string normalized = Normalize(jid);
            if (string.IsNullOrWhiteSpace(normalized) ||
                !normalized.EndsWith("@s.whatsapp.net", StringComparison.OrdinalIgnoreCase))
            {
                return null;
            }

            int at = normalized.IndexOf('@');
            if (at <= 0)
            {
                return null;
            }

            return normalized.Substring(0, at);
        }

        public static bool IsGroupJid(string jid)
        {
            string normalized = Normalize(jid);
            return !string.IsNullOrEmpty(normalized) &&
                   normalized.EndsWith("@g.us", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Resolves list category: Group → Personal (self) → Direct.
        /// </summary>
        public static ChatKind ResolveKind(string jid, bool isSelfChat)
        {
            if (IsGroupJid(jid))
            {
                return ChatKind.Group;
            }

            if (isSelfChat)
            {
                return ChatKind.Personal;
            }

            return ChatKind.Direct;
        }
    }
}
